### ISSUE TITLE
I want use you lib within stdperiph 1.02

### ISSUE THREAD

**Issue by jiuxiaxixi** [MaJerle/stm32f429#10]
what will happened if I use a lower stdperiph?

**Comment by jiuxiaxixi** [comment]
could I replace some files which I will use?

**Comment by MaJerle** [comment]
Im not sure I understand your quesrion.

**Comment by jiuxiaxixi** [comment]
Thanks a lot, my problem has been solved!

**Comment by MaJerle** [comment]
Why don't you share info what was the problem and what the resolution?

**Comment by jiuxiaxixi** [comment]
I am not sure the if the USB Library was compatible with the STM32F4xx_StdPeriph_Driver version 1.02, and I had developed USB2CAN  based on the version 1.02. But I want using your USART with DMA, so I try to upgrade the STM32F4xx_StdPeriph_Driver version to 1.7.

I found that the USB library is independent with the STM32F4xx_StdPeriph_Driver.
Thanks a lot, your work is so fantastic to me!

**Comment by jiuxiaxixi** [comment]
And I have something that I thought cool. The SPI driver.
I think the way of using that is so cool
![image](https://user-images.githubusercontent.com/13214300/27674554-d712b7b8-5cd8-11e7-9c48-e36c8f35c485.png)

[rhb_spi_bus_adapter.c.txt](https://github.com/MaJerle/stm32f429/files/1111075/rhb_spi_bus_adapter.c.txt)
[rhb_spi_bus_adapter.h.txt](https://github.com/MaJerle/stm32f429/files/1111078/rhb_spi_bus_adapter.h.txt)

**Comment by jiuxiaxixi** [comment]
@MaJerle
