### ISSUE TITLE
stm32f4-discovery website is missing

### ISSUE THREAD

**Issue by MattiaFailla** [MaJerle/stm32f429#14]
Hey, I just noticed that [stm32f website](http://www.stm32f4-discovery.com/) is unavailable. 
Are there any other good website to visit?

**Comment by un1tyNL** [comment]
That's because you're using the incorrect URL... 
The correct URL is https://stm32f4-discovery.net

**Comment by MattiaFailla** [comment]
If you try you can find out that almost every link on this repo redirect to my link.. 
Anyway, thanks for the suggestion.

**Comment by MaJerle** [comment]
To avoid such problems in future, here is a new commit. https://github.com/MaJerle/stm32f429/commit/c6a9a5b1a100b9c6dc03b859c1110fc41ff2b534
