### ISSUE TITLE
Extern "C" wrapper missing in delay.c and delay.h

### ISSUE THREAD

**Issue by JonathanGoldnauVogt** [MaJerle/stm32f429#4]
Delay library doesn't work in C++ but doesn't throw linking error due to __weak function definition in STD library. 

Suggested fix is adding wrapper to .c and .h
Thanks.

**Comment by MaJerle** [comment]
What is the error?

**Comment by MaJerle** [comment]
What is the error?

**Comment by JonathanGoldnauVogt** [comment]
There is no error. Which made it harder to debug.
If you download your default project and run it on a discovery-F4 with
parameters "--cpp" the LEDs stay on and do not blink. The systick handler
is not being called properly. I believe the definition of
"__weak void TimingDelay_Decrement" is suppressing a linking error.
Adding extern "C" fixes the issue.

**Comment by MaJerle** [comment]
I have added extern "C" in delay library.

Thanks for reporting issue.
