### ISSUE TITLE
Definitons?

### ISSUE THREAD

**Issue by golddragon007** [MaJerle/stm32f429#6]
Hello,

How can I use this in eclipse, because it seems there are some definition which are in the .lib file... Or how can I extract those?

Thanks.

**Comment by MaJerle** [comment]
Use what actually?

**Comment by golddragon007** [comment]
I want to use the Library 09- I2C and I downloaded from here: http://stm32f4-discovery.com/2014/05/library-09-i2c-for-stm32f4xx/ the TM STM32F4 I2C Library rar file. The problem is, when I add to my project the *.c and *.h files in the eclipse, I get not defined variables, like ADC_SOFTWARE_START . (which is in the tm_stm32_esp8266_keil.lib file, which I can't use, because I using eclipse, not keil...) any solution?

**Comment by MaJerle** [comment]
.lib is not for gcc build. Use esp8266at.com for esp library.
