### ISSUE TITLE
Bug in TM_SPI_Send16 prototype

### ISSUE THREAD

**Issue by PoZitron** [MaJerle/stm32f429#8]
Hello.
Seems you have typo in prototype of function TM_SPI_Send16 in Library 05- SPI for STM32F4. You have:
`static __INLINE uint16_t TM_SPI_Send16(SPI_TypeDef* SPIx, uint8_t data)`
We are trying to send 16-bit data, so uint8_t is wrong type here. Correct:
`static __INLINE uint16_t TM_SPI_Send16(SPI_TypeDef* SPIx, uint16_t data)`
Bug introduced in [ec852fe6aaa7a3b9785dc1e41825a1be74843cfa](https://github.com/MaJerle/stm32f429/commit/ec852fe6aaa7a3b9785dc1e41825a1be74843cfa#diff-d4c74364f3dcbcd686c52bfe3d4c8b70L440)

**Comment by MaJerle** [comment]
True.
